# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    labels:
      - "dependabot"
      - "github-actions"
    assignees:
      - "akelbikhanov"
    groups:
      actions-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    labels:
      - "dependabot"
      - "go"
    assignees:
      - "akelbikhanov"
    groups:
      go-dependencies:
        patterns:
          - "*"