version: "2"  # Версия схемы конфигурации. Обязательно для golangci-lint v2+

run:
  timeout: 2m  # Максимальное время выполнения линтеров (2 минуты)
  tests: true  # Проверять также *_test.go файлы

linters:
  enable:
    - govet       # Встроенный инструмент Go — проверяет подозрительные конструкции
    - errcheck    # Проверяет, что ошибки не игнорируются
    - staticcheck # Расширенный анализатор от Dominik Honnef (совмещает vet, gosimple и др.)
    - unused      # Ищет неиспользуемые переменные, функции, импорты
    - gocritic    # Набор best practices и подозрительных конструкций
    - revive      # Проверка стиля и документации (замена golint)

  exclusions:
    rules:
      # Игнорировать некоторые линтеры в тестах
      - path: '_test\.go'       # Применяется ко всем файлам, заканчивающимся на _test.go
        linters:
          - errcheck            # В тестах допустимо игнорировать ошибки
          - staticcheck         # Некоторые проверки не критичны для тестов

formatters:
  enable:
    - gofmt  # Проверка форматирования кода как gofmt
    - gci    # Проверка порядка импортов и их группировки

issues:
  max-issues-per-linter: 0  # Без ограничения на кол-во ошибок от одного линтера
  max-same-issues: 0        # Без ограничения на повторяющиеся ошибки
