version: "1"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gofmt
    - gocritic
    - revive        # альтернатива golint
    - gci           # более строгая работа с импортами

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false

exclude-rules:
  # Не ругаться на errcheck и staticcheck в тестах
  - path: _test\.go
    linters:
      - errcheck
      - staticcheck

  # Исключить ошибки в файлах сгенерированного кода (по шаблону)
  - path: "internal/.*_gen.go"
    linters:
      - all

  # Пример исключения для файлов миграций, если появятся
  - path: "migrations/.*\.go"
    linters:
      - revive
      - gocritic
