linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gofmt
    - goimports
    - gocritic

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true