apiVersion: apps/v1                         # API-группа и версия для Deployment
kind: Deployment                            # описание ресурса Deployment
metadata:
  name: exrubbot                            # имя Deployment
  labels:
    app: exrubbot                           # метка для селектора и группировки
spec:
  replicas: 1                               # количество подов в ReplicaSet
  selector:
    matchLabels:
      app: exrubbot                         # метка, по которой Deployment находит управляемые поды
  template:                                 # шаблон создаваемых подов
    metadata:
      labels:
        app: exrubbot                       # метки, присваиваемые каждому создаваемому поду
    spec:
      restartPolicy: Always                 # политика перезапуска контейнера при сбое
      containers:
        - name: exrubbot                    # имя контейнера внутри пода
          image: ghcr.io/akelbikhanov/exrubbot:v1.0.2  # образ и тег контейнера
          imagePullPolicy: IfNotPresent     # политика подтягивания образа
          env:
            - name: EXRUBBOT_TOKEN          # переменная окружения для токена бота
              valueFrom:
                secretKeyRef:
                  name: exrubbot-secrets    # имя секрета с токеном
                  key: EXRUBBOT_TOKEN       # ключ в секрете
          resources:
            limits:
              memory: "128Mi"               # лимит по памяти для контейнера
              cpu: "200m"                   # лимит по CPU для контейнера
          volumeMounts:
            - name: data                    # имя тома для монтирования
              mountPath: /data              # путь в контейнере, куда монтируется том
      volumes:
        - name: data                        # том, объявленный для пода
          persistentVolumeClaim:
            claimName: exrubbot-pvc         # ссылка на PVC для монтирования тома