# .github/workflows/CD-production.yml
name: CD-production

on:
  workflow_run:
    workflows: ['CI']
    types: [completed]

permissions:
  contents: read
  packages: write

concurrency:
  group: production-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-and-push:
    if: >
      github.event_name == 'workflow_run' &&
      github.event.workflow_run.name == 'CI' &&
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.ref_name, 'v')
    runs-on: ubuntu-latest
    steps:
      # получаем точный коммит по тегу
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      # Buildx
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      # Логин в GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Сборка + пуш образа с кэшем, SBOM и provenance
      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          sbom: true
          provenance: mode=max
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:latest
