# .github/workflows/CI.yml
name: CI

on:
  push:
    branches: [main]
    tags-ignore: ['*']
  pull_request:
    branches: [main]
  workflow_call:

permissions:
  contents: read

concurrency:
  # CI-refs/heads/main
  # CI-refs/pull/123/head
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Go & cache modules
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Run linters
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --config .golangci.yml --concurrency 4

  test:
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Go & cache modules
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Run tests
        run: go test -v ./...
