# .github/workflows/cleanup-images.yml
name: cleanup-images
on:
  schedule:
    - cron: '0 0 * * *' # Ежедневно в 00:00 UTC
  workflow_dispatch:    # Ручной запуск

permissions:
  packages: write

jobs:
  cleanup-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old staging images
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ github.repository }}
          package-type: container
          min-versions-to-keep: 5
          ignore-versions: |
            ^latest$
            ^v\d+\.\d+\.\d+(-.+)?$
          token: ${{ secrets.GITHUB_TOKEN }}

  cleanup-stable:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old stable images
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ github.repository }}
          package-type: container
          min-versions-to-keep: 5
          ignore-versions: |
            ^staging.*$
          token: ${{ secrets.GITHUB_TOKEN }}
