# .github/workflows/release.yml
name: release

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

concurrency:
  group: release-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/CI.yml
    permissions:
      contents: read

  build-and-push:
    needs: ci
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.target_commitish }}
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          sbom: false
          provenance: false
          build-args: |
            VERSION=${{ github.event.release.tag_name }}
            GIT_COMMIT=${{ github.sha }}
            BUILD_TIME=${{ github.run_started_at }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
            ghcr.io/${{ github.repository }}:latest