# .github/workflows/staging-cleanup.yml
name: staging-cleanup
on:
  schedule:
    - cron: '0 0 * * *' # Ежедневно в 00:00 UTC
  workflow_dispatch:    # Ручной запуск

permissions:
  packages: write

jobs:
  cleanup-others:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ github.event.repository.name }}
          package-type: container
          min-versions-to-keep: 0
          # сохраняем только latest, релизы и staging-версии
          ignore-versions: |
            ^latest$
            ^v\d+\.\d+\.\d+(-.+)?$
            ^staging-[0-9a-f]+$
          token: ${{ secrets.GITHUB_TOKEN }}

  cleanup-staging:
    needs: cleanup-others
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ github.event.repository.name }}
          package-type: container
          min-versions-to-keep: 5
          # теперь из staging-* оставляем только 5 последних
          ignore-versions: |
            ^latest$
            ^v\d+\.\d+\.\d+(-.+)?$
          token: ${{ secrets.GITHUB_TOKEN }}
