# .github/workflows/staging.yml
name: staging

on:
  push:
    branches: ['staging']

permissions:
  contents: read
  packages: write

concurrency:
  group: staging-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/CI.yml
    permissions:
      contents: read

  build-and-push:
    needs: ci
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate timestamp from run start
        id: timestamp
        run: |
          echo "build_time=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT
          echo "formatted=$(date -u +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          sbom: false
          provenance: false
          build-args: |
            VERSION=staging-${{ steps.timestamp.outputs.formatted }}
            GIT_COMMIT=${{ github.sha }}
            BUILD_TIME=${{ steps.timestamp.outputs.build_time }}
          tags: |
            ghcr.io/${{ github.repository }}:staging-${{ steps.timestamp.outputs.formatted }}